name: Build Redis Docker image

on:
  push:
    branches: [ "main", "devops" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker version
        pwd
        ls -l
        cd bitnami/redis/8.2/debian-12
        echo 'docker build . --file Dockerfile --tag my-image-name:$(date +%s)'
