name: Build Redis Docker image
env:
  REGION: asia
  REGISTRY_REPO: e4m-repo

on:
  push:
    branches: [ "main", "devops" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build the Docker image
      run: |
        docker version
        pwd
        ls -l
        cd bitnami/redis/8.2/debian-12
        ls -l
        docker image ls
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REGISTRY_REPO:${GITHUB_SHA::7} \
        -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REGISTRY_REPO:latest .
        docker image ls

    - name: Push to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REGISTRY_REPO:${GITHUB_SHA::7}
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REGISTRY_REPO:latest