name: Build Redis Docker image
env:
  REGISTRY_REPO: vhv

on:
  push:
    branches: [ "main", "devops" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker version
        pwd
        ls -l
        cd bitnami/redis/8.2/debian-12
        ls -l
        docker image ls
        docker build -t $REGISTRY_REPO:$SHORT_SHA -t $REGISTRY_REPO:latest .
        docker image ls
